spring.application.name=expensetracker

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/newexpensetracker
spring.datasource.username=root
spring.datasource.password=110205

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
